### PR TITLE
Upgrade to .Net 4.7

### PR DESCRIPTION
**Pull request by CDAGaming**
Signed-off-by: CDAGaming <cstack2011@yahoo.com>

### CODE REVIEW

**Comment by Furtif** [comment]
@CDAGaming  integrate this #47 and close #47

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/POGOProtos/subscription

**Comment by CDAGaming** [comment]
Oh, add those changes to this pr @Furtif . Well, at this time i am packing for travelling tomorrow so ill have to find a time tonight when i can

**Comment by CDAGaming** [comment]
Will Reopen Tomorrow

**Pull request closed without merging**
